---

- hosts: all 
  gather_facts: yes
  become: yes
  roles:
    - { role: all }


- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: master }

- hosts: osds
  gather_facts: no
  become: yes
  vars:
        - ansible_password: '$6$NJ9wJWlh$8bV5radDt4eNrutVgoa8kOHCwRJEPFnBPyyDDDhdLlXHUnro1Nj1kWbnxbOT5zZHd.vbUwsguk2MJvw5eqe3m1'
  roles:
    - { role: osds }
